# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit journal.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tagtools)
library(plotly)
library(stats)
library(ggplot2)

