# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Convolution (in C++)
#' @description Performs 1D convolution of two vectors in C++ via FFT.
#' @param a The first numeric vector.
#' @param b The second numeric vector.
#' @param shape (optional) The shape of the output: "full", "same", or "valid". Default is "full," matching \code{\link[signal]{conv}} and the Armadillo default, which means that the output array is \code{length(a)} + \code{length(b)} - 1.
#' @return A numeric vector containing the convolution result.
#' @export
conv_cpp <- function(a, b, shape = "full") {
    .Call(`_tagtools_conv_cpp`, a, b, shape)
}

